### ISSUE TITLE
Complete language support for all 96%+ languages

### ISSUE THREAD

**Issue by davelab6** [productiontype/Spectral#4]
I'd like to request just a few languages which have over 90% character support and are just missing a few characters, according to CLDR :)

| Language (code) | Coverage | %Coverage | Missing Characters |
| ---- | ---- | ---- | ---- |
| French (fr) | 112/113 | 99 | \u01d4 (ǔ) |
| Norwegian (no) | 104/105 | 99 | \u01ce (ǎ) |
| Kyrgyz (ky) | 102/103 | 99 | \u04a3 (ң) |
| Mongolian (mn) | 69/70 | 98 | \u04ca (ӊ) |
| Hungarian (hu) | 130/133 | 97 | \u2052 (⁒), \u27e8 (⟨), \u27e9 (⟩) |
| Macedonian (mk) | 83/85 | 97 | \u0450 (ѐ), \u045d (ѝ) |
| Bulgarian (bg) | 89/92 | 96 | \u0450 (ѐ), \u045d (ѝ), \u046b (ѫ) |
| Finnish (fi) | 157/162 | 96 | \u021f (ȟ), \u0292 (ʒ), \u01e5 (ǥ), \u01e9 (ǩ), \u01ef (ǯ) |

**Comment by productiontype** [comment]
Will check this out. (Still need to find a French word that has an ǔ)

**Comment by davelab6** [comment]
If CLDR is wrong, we should fix that :)

Already found one bug from this round of work, https://unicode.org/cldr/trac/ticket/10739

**Comment by moyogo** [comment]
@davelab You shouldn't use the auxiliary exemplar characters. They're often completely random as they include characters from other languages that may be extremely rare (borrowed words or proper nouns are most often simplified).

**Comment by davelab6** [comment]
@moyogo http://cldr.unicode.org/translation/characters#TOC-Exemplar-Characters says.

> For example, you could see the name Schröder in English in a magazine, so ö is in the set. However, it is very uncommon to see ł, so that isn't in the auxiliary set for English. 

I understood that they are rare but common enough to be worth including... 

cc @roozbehp

**Comment by moyogo** [comment]
For ǔ in French, it sounds like an unlikely character. It's used in some African languages spoken where French is spoken, that's basically why it ends up in some CLDR French locales auxiliary exemplars. It's extremely unlikely to show up in "French" text.

**Comment by davelab6** [comment]
Ah that makes sense - so then this is a bug with CLDR :) https://unicode.org/cldr/trac/ticket/10793

**Comment by moyogo** [comment]
Honestly, I don’t know whether that character should be removed from the French auxiliary set. I think the auxiliary exemplar sets are inconsistent from one CLDR locale to another and shouldn’t be used to decide whether a language is covered or not.
The definition of the auxiliary set leave a lot of wiggle room. For some languages some kind of "magazine" have been excluded while for others they might not have been.
Why are ā ē ī in the French auxiliary set, why aren’t ō ū? The CLDR provides no reference why that decision was made.

Other issues in the set you show are:
- \u01ce (ǎ) is not used in Norwegian or in the area of Norway, as far as I know.
- \u04ca (ӊ) is not used in Mongol, the closest and only use is Kildin Sami in Western Russia — Western not Eastern, Mongolia is East. Maybe it should have been \u04a3 (ң) since that is used in Kalmuk, spoken in Mongolia, or in languages in the area of Mongolia.
- \u021f (ȟ), \u0292 (ʒ), \u01e5 (ǥ), \u01e9 (ǩ), \u01ef (ǯ) are used in Sami languages or Romani languages spoken in Finland or the area.

I’d also take punctuation exemplar sets with care. I doubt Hungarian uses \u27e8 ⟨ and \u27e9 ⟩ more than other languages yet they have same mathematical or linguistic use.

**Comment by davelab6** [comment]
Okay, so there is lots of work to do on cldr :)

How easily can you provide references for all these assertions, or should I
reference simply this comment to get them removed?

**Comment by moyogo** [comment]
Maybe there's a better place to discuss this :-)

My main point about the auxiliary exemplar character sets is that they just define characters that may occur in those languages but they are absolutely not required to cover those languages. So I’d recommend ignoring the auxiliary exemplar character sets for calculating Spectral’s language support.

**Comment by davelab6** [comment]
Okay, got it. I'll file an issue on the internal language check tool from where this is from 

@graphicore does your language check tool already do this?

**Comment by graphicore** [comment]
> @graphicore does your language check tool already do this?

Yeah, I'm ignoring `auxiliary`. I just need to look at the `de` locale:

```
"auxiliary": "[á à ă â å ã ā æ ç é è ĕ ê ë ē ğ í ì ĭ î ï İ ī ı ñ ó ò ŏ ô ø ō œ ş ú ù ŭ û ū ÿ]",
```

None of these would be considered characters needed to write German, it's more like a collection of characters used in languages of neighboring countries (which is why they are found in German text corpses I guess.) 

I'm using `exemplarCharacters` and `punctuation` also numbers via `cldr-numbers-modern` and `cldr-core/supplemental/numberingSystems`. 

> I’d also take punctuation exemplar sets with care. I doubt Hungarian uses \u27e8 ⟨ and \u27e9 ⟩ more than other languages yet they have same mathematical or linguistic use.

Still the best data we have. In the language check tool we include exceptions for our "lax" detection style for things like this.

**Comment by davelab6** [comment]
http://unicode.org/cldr/trac/ticket/10793#comment:2 says that ǔ will be kept, and as such, I'll now consider auxiliary characters garbage and ignore them completely.
